repos:
  - repo: local
    hooks:
      - id: spotless-check
        name: spotless-check
        entry: mvn spotless:check
        language: system
        pass_filenames: false
        types: [java]
