services:
  cg4j:
    build:
      context: .
      dockerfile: Dockerfile
    image: cg4j:latest
    volumes:
      - ${INPUT_DIR}:/input:ro
      - ${OUTPUT_DIR}:/output
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx2g
