site_name: CG4j
site_url: https://cg4j.net

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Call Graphs Basics: callgraph-basics.md

theme:
  name: material
  language: en
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.tabs.sticky

copyright: Copyright &copy; 2026

extra_css:
  - css/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

