site_name: CG4j
site_url: https://cg4j.net
repo_url: https://github.com/cg4j/cg4j
repo_name: cg4j/cg4j

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Call Graphs Basics: callgraph-basics.md

theme:
  name: material
  language: en
  logo: assets/cg4j-logo.svg
  favicon: assets/cg4j-logo.svg
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.tabs.sticky

copyright: Copyright &copy; 2026

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cg4j/cg4j
      name: CG4j on GitHub
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/cg4j_net
      name: CG4j on X

extra_css:
  - css/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - kroki:
      server_url: https://kroki.io
      fence_prefix: kroki-
